[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[features]
default = ["desktop"]
desktop = ["iced_video_player"]
web = []

[dependencies]
iced = "0.13.1"
iced_video_player = { version = "0.5.0", optional = true }
url = "2.5.4"
