[package]
name = "backend"
version = "0.1.0"
edition = "2024"
resolver = "3"

[dependencies]
axum = "0.8"
tokio = { version = "1.0", features = ["full"] }
tower-http = { version = "0.6", features = ["fs", "trace", "cors"] }
